// Code generated by "stringer -type=Direction -linecomment"; DO NOT EDIT.

package aseprite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayForward-0]
	_ = x[PlayReverse-1]
	_ = x[PlayPingPong-2]
}

const _Direction_name = "forwardreversepingpong"

var _Direction_index = [...]uint8{0, 7, 14, 22}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
